using System;

namespace UnityEngine.UIElements.StyleSheets
{
	internal enum StylePropertyId
	{
		Unknown = -1,
		Custom = -2,
		AlignContent = 65536,
		AlignItems,
		AlignSelf,
		BackgroundColor,
		BackgroundImage,
		BorderBottomColor,
		BorderBottomLeftRadius,
		BorderBottomRightRadius,
		BorderBottomWidth,
		BorderColor = 131072,
		BorderLeftColor = 65545,
		BorderLeftWidth,
		BorderRadius = 131073,
		BorderRightColor = 65547,
		BorderRightWidth,
		BorderTopColor,
		BorderTopLeftRadius,
		BorderTopRightRadius,
		BorderTopWidth,
		BorderWidth = 131074,
		Bottom = 65553,
		Color = 0,
		Cursor = 65554,
		Display,
		Flex = 131075,
		FlexBasis = 65556,
		FlexDirection,
		FlexGrow,
		FlexShrink,
		FlexWrap,
		FontSize = 1,
		Height = 65561,
		JustifyContent,
		Left,
		Margin = 131076,
		MarginBottom = 65564,
		MarginLeft,
		MarginRight,
		MarginTop,
		MaxHeight,
		MaxWidth,
		MinHeight,
		MinWidth,
		Opacity,
		Overflow,
		Padding = 131077,
		PaddingBottom = 65574,
		PaddingLeft,
		PaddingRight,
		PaddingTop,
		Position,
		Right,
		TextOverflow,
		Top,
		UnityBackgroundImageTintColor,
		UnityBackgroundScaleMode,
		UnityFont = 2,
		UnityFontStyleAndWeight,
		UnityOverflowClipBox = 65584,
		UnitySliceBottom,
		UnitySliceLeft,
		UnitySliceRight,
		UnitySliceTop,
		UnityTextAlign = 4,
		UnityTextOverflowPosition = 65589,
		Visibility = 5,
		WhiteSpace,
		Width = 65590
	}
}
